version: '3'
services:

  bp-postgres:
    image: "postgres:latest"
    platform: linux/amd64
    container_name: bp-postgres
    volumes:
      - bp-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bp
      - POSTGRES_PASSWORD=bp
volumes:
  bp-data:
